### ISSUE TITLE
Mutable Rectangle?

### ISSUE THREAD

**Issue by Chris3606** [Jjagg/OpenWheels#8]
I just noticed that the `Rectangle` class in the main OpenWheels project was changed to be mutable (although the 2D point was not).  Given that mutable structs can lead to some unexpected and non-performant behavior, I was curious, why make either mutable?

**Comment by Jjagg** [comment]
> Given that mutable structs can lead to some unexpected and non-performant behavior

I did it for convenience, but I plan on reverting the change. I pass `Rectangle(F)` instances with `in` everywhere and that causes defensive copies being made when calling instance methods. The motivation was to prevent making a copy when changing a field of the `Rectangle`, but that doesn't happen nearly as often as passing by `in` and then calling instance methods. Thanks for you interest :)

**Comment by Chris3606** [comment]
Thanks 😁 Yeah, I maintain a [roguelike/2d grid-game-oriented library](https://github.com/Chris3606/GoRogue/tree/master/GoRogue), that (at least for the moment) defines its own primitives for things like point and rectangle. I had experimented with mutable structs awhile back for `Rectangle`, and the side effects of the defensive copying combined with mutability became a nightmare.

Immutable struct does mean more copying of course, however the copying of a rectangle (4 ints) is actually not near as bad as you might think when it's a value type

**Comment by Chris3606** [comment]
Also, I did want to say, I really love the idea of a purely primitives library like this.  I'm actually hoping, somewhere down the line, to move my library to use your primitives instead of my current versions of Point and Rectangle :D

**Comment by Jjagg** [comment]
Awesome :)
I'm just looking for a good way to abstract font rendering, then I'll try to get the API stable so this thing can actually be used.

**Comment by Jjagg** [comment]
Fixed in bfa483007d7289634928b07ce0d0a1212bbd0191.
